version: '3'
services:
  postgres:
    image: postgres:12
    env_file:
      - .env/vars
    ports:
      - 5433:5432 # don't conflict with the running Postgres instance on host machine
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
  redis:
    image: redis:latest
    env_file:
      - .env/vars
    ports:
      - 6379:6379
    volumes:
      - ./.data/redis:/data
  elasticsearch:
    image: elasticsearch:7.13.1
    env_file:
      - .env/vars
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./.data/elasticsearch:/usr/share/elasticsearch/data
  neo4j:
    container_name: neo4j
    image: neo4j:latest
    env_file: .env/vars
    volumes:
      - ./plugins:/plugins
      - ./data/neo4j:/data
      - ./import:/import
    ports:
      - 7474:7474
      - 7687:7687