version: '3'
services:
  api:
    build: .
    env_file:
      - .env/vars
    volumes:
      - .:/app
      - ./assets:/app/assets
      - ./media:/app/media
    depends_on:
      - postgres
      - redis
      - elasticsearch
  celery:
    build: .
    command: celery -A breaking_brain_api worker -l info
    env_file:
      - .env/vars
    entrypoint: ""
    volumes:
      - .:/app
    depends_on:
      - redis
      - api
  celery_beat:
    build: .
    command: celery -A breaking_brain_api beat -l info
    env_file:
      - .env/vars
    entrypoint: ""
    volumes:
      - .:/app
    depends_on:
      - redis
      - api
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env/vars
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
  redis:
    image: redis:latest
    env_file:
      - .env/vars
    volumes:
      - ./.data/redis:/data
  elasticsearch:
    image: elasticsearch:7.13.1
    env_file:
      - .env/vars
    environment:
      - discovery.type=single-node
    volumes:
      - ./.data/elasticsearch:/usr/share/elasticsearch/data
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    env_file:
      - .env/vars
    volumes:
      - ./.conf/nginx:/etc/nginx/conf.d
      - ./assets:/app/assets
      - ./media:/app/media
    depends_on:
      - api