# Generated by Django 3.1.5 on 2021-03-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_auto_20210301_2014'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tags',
            field=models.ManyToManyField(related_name='users', to='quizzes.Tag'),
        ),
    ]
