# Generated by Django 3.1.5 on 2021-06-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_lesson'),
        ('authentication', '0002_user_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(related_name='users', to='quizzes.Quiz'),
        ),
    ]
