# Generated by Django 3.1.5 on 2021-06-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_auto_20210613_1723'),
        ('authentication', '0003_user_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bought_quizzes',
            field=models.ManyToManyField(related_name='buyers', to='quizzes.Quiz'),
        ),
    ]
